moivie/moivie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.MEDIA_ROOT)

moivie/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns =[

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

moivie/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img = models.ImageField(upload_to='gllery')

    def __str__(self):

        return self.name

moivie/movieapp/forms.py
from django import forms
from .models import movie


class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name','desc','year','img']

moivie/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import movieform


# Create your views here.


def index(request):
    Movie = movie.objects.all()
    context = {
        'movie_list': Movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movies = movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movies': movies})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        Movie = movie(name=name, desc=desc, year=year, img=img)
        Movie.save()

    return render(request, "add.html")
def update(request,id):
    Movie = movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'Movie':Movie})


def delete(request,id):
    if request.method== 'POST':
        Movie =movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

moivie/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add data</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your name" ><br>
    <input type="text" name="desc" placeholder="enetr description"><br>
    <input type="text" name="year" placeholder="enter movie relaese year"><br>
    <input type="file" name="img"><br>
    <input type="submit">

</form>
</body>
</html>

moivie/templates/css.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

moivie/templates/delete.html
<form method="post" >
    {% csrf_token %}
    are you want to delete this movie?\
    <input type="submit">

</form>

moivie/templates/details.html
{% extends 'css.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{i.img.url}}" width="1000" height="1000">
        </div>
        <div class="col-md-6">
            {{movies.name}}
                            <br>
            {{movies.year}}
                            <br>
            {{movies.desc}}<br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movies.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movies.id %}">delete</a>
        </div>
    </div>
</div>

{% endblock %}

moivie/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

moivie/templates/index.html
{% extends 'css.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="100px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">edit/delete</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>





<a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">add movie</a>
{% endblock %}